export type Bookmark = {
  id: string;
  title: string;
  url: string;
  category: string;
  description: string;
  image: string;
  'data-ai-hint'?: string;
};

export const bookmarks: Bookmark[] = [
  {
    id: '1',
    title: 'YouTube',
    url: 'https://www.youtube.com/',
    category: 'Homepage',
    description: 'Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'video streaming',
  },
  {
    id: '2',
    title: 'Google Photos',
    url: 'https://photos.google.com/',
    category: 'Homepage',
    description: 'A home for all your photos and videos, automatically organized and easy to share.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'photo gallery',
  },
  {
    id: '3',
    title: 'CHD4',
    url: 'https://www.chd4.com/index.php',
    category: 'Homepage',
    description: 'Website link for chd4.com.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'abstract tech',
  },
  {
    id: '4',
    title: 'Messenger',
    url: 'https://www.messenger.com/t/100010933336595/',
    category: 'Homepage',
    description: 'Hang out anytime, anywhere—Messenger makes it easy and fun to stay close to your favorite people.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'chat bubbles',
  },
  {
    id: '5',
    title: 'Instagram',
    url: 'https://www.instagram.com/?hl=en',
    category: 'Homepage',
    description: 'A simple, fun & creative way to capture, edit & share photos, videos & messages with friends & family.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'social media',
  },
  {
    id: '6',
    title: 'ChatGPT',
    url: 'https://chatgpt.com/',
    category: 'AI',
    description: 'A large language model-based chatbot developed by OpenAI.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'AI robot',
  },
  {
    id: '7',
    title: 'Claude AI',
    url: 'https://claude.ai/login',
    category: 'AI',
    description: 'A next-generation AI assistant for your tasks, no matter the scale.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'friendly AI',
  },
  {
    id: '8',
    title: 'GitHub Copilot',
    url: 'https://github.com/copilot',
    category: 'AI',
    description: 'Your AI pair programmer. Get suggestions for whole lines or entire functions right in your editor.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'coding assistant',
  },
  {
    id: '9',
    title: 'Daud',
    url: 'https://daudibrahim.com/',
    category: 'Homepage',
    description: 'Personal website.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'portfolio website',
  },
  {
    id: '10',
    title: 'AIUB Portal',
    url: 'https://portal.aiub.edu/',
    category: 'Education',
    description: 'Official student portal for American International University-Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'university campus',
  },
  {
    id: '11',
    title: 'TorrentBD',
    url: 'https://www.torrentbd.net/',
    category: 'Entertainment',
    description: 'A torrent website.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie film',
  },
  {
    id: '12',
    title: 'Google Translate',
    url: 'https://translate.google.com/?sl=bn&tl=en&op=translate',
    category: 'Utilities',
    description: 'Google\'s free service instantly translates words, phrases, and web pages.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'language translation',
  },
  {
    id: '13',
    title: 'Router Login',
    url: 'http://192.168.0.1/',
    category: 'Utilities',
    description: 'Local network router access page.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'network router',
  },
  {
    id: '14',
    title: 'Login - RDMS',
    url: 'https://dms.robi.com.bd/#/login',
    category: 'Work',
    description: 'Login page for RDMS.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'secure login',
  },
  {
    id: '15',
    title: 'LinkedIn',
    url: 'https://www.linkedin.com/feed/',
    category: 'Social',
    description: 'Manage your professional identity. Build and engage with your professional network.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'professional networking',
  },
  {
    id: '16',
    title: 'WhatsApp',
    url: 'https://web.whatsapp.com/',
    category: 'Social',
    description: 'A freeware, cross-platform messaging and Voice over IP service.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'messaging app',
  },
  {
    id: '17',
    title: 'DeepSeek',
    url: 'https://chat.deepseek.com/',
    category: 'AI',
    description: 'An AI research lab with a mission to explore the frontiers of intelligence.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'deep learning',
  },
  {
    id: '18',
    title: 'Microsoft Copilot',
    url: 'https://copilot.cloud.microsoft/',
    category: 'AI',
    description: 'Your everyday AI companion.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'AI assistant',
  },
  {
    id: '19',
    title: 'Facebook',
    url: 'https://www.facebook.com/Shawoncomputersbd/',
    category: 'Apps',
    description: 'A social networking site that makes it easy for you to connect and share with family and friends online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'social network',
  },
  {
    id: '20',
    title: 'Messenger',
    url: 'https://www.messenger.com/',
    category: 'Apps',
    description: 'A messaging app and platform. Connect with your favorite people.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'chatting online',
  },
  {
    id: '21',
    title: 'Gmail',
    url: 'https://accounts.google.com/b/0/AddMailService',
    category: 'Apps',
    description: 'A free email service provided by Google.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'email inbox',
  },
  {
    id: '22',
    title: 'Maps',
    url: 'https://maps.google.com/',
    category: 'Apps',
    description: 'A web mapping service developed by Google.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'world map',
  },
  {
    id: '23',
    title: 'Microsoft Teams',
    url: 'https://teams.microsoft.com/_?culture=en-us&country=WW&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn#/apps/66aeee93-507d-479a-a3ef-8f494af43945/sections/classroom',
    category: 'Apps',
    description: 'The hub for team collaboration in Microsoft 365.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'team collaboration',
  },
  {
    id: '24',
    title: 'Dashboard | Freelancer',
    url: 'https://www.freelancer.com.bd/dashboard',
    category: 'Work',
    description: 'Hire freelance programmers, web developers, designers, writers, data entry & more.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'freelance work',
  },
  {
    id: '25',
    title: 'TikTok - Make Your Day',
    url: 'https://www.tiktok.com/en/',
    category: 'Social',
    description: 'A social media platform for creating, sharing and discovering short videos.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'video clips',
  },
  {
    id: '26',
    title: 'Google Images',
    url: 'https://www.google.com.bd/imghp?hl=en&tab=ri&authuser=0&ogbl',
    category: 'Utilities',
    description: 'The most comprehensive image search on the web.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'image search',
  },
  {
    id: '27',
    title: 'YouTube',
    url: 'https://youtube.com/',
    category: 'Entertainment',
    description: 'Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online video',
  },
  {
    id: '28',
    title: 'Adobe Acrobat Home',
    url: 'https://acrobat.adobe.com/link/home/',
    category: 'Utilities',
    description: 'The best PDF editor to edit and create PDFs.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'pdf document',
  },
  {
    id: '29',
    title: 'Quotex: An innovative platform for online investment',
    url: 'https://qxbroker.com/en/trade',
    category: 'Trading',
    description: 'Quotex is a new-level trading platform.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'investment charts',
  },
  {
    id: '30',
    title: 'Forefront Chat',
    url: 'https://chat.forefront.ai/',
    category: 'AI',
    description: 'Free access to GPT-4, image generation, custom personas, and more.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai chat',
  },
  {
    id: '31',
    title: 'AIUB Connect',
    url: 'https://aiubconnect.com/login/welcome.html',
    category: 'Education',
    description: 'Login for AIUB Connect.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'university login',
  },
  {
    id: '32',
    title: 'Dhaka Stock Exchange',
    url: 'https://www.dsebd.org/',
    category: 'Trading',
    description: 'The prime stock exchange of Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'stock market',
  },
  {
    id: '33',
    title: 'StockNow | Your Investment Assistant',
    url: 'https://stocknow.com.bd/',
    category: 'Trading',
    description: 'Real-time stock market data and analytics.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'financial data',
  },
  {
    id: '34',
    title: 'Binance - Cryptocurrency Exchange',
    url: 'https://www.binance.com/en',
    category: 'Trading',
    description: 'The World\'s Leading Cryptocurrency Exchange.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cryptocurrency coins',
  },
  {
    id: '35',
    title: 'TradingView — Track All Markets',
    url: 'https://www.tradingview.com/',
    category: 'Trading',
    description: 'Charts, forecasts and trading ideas from other traders.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'market analysis',
  },
  {
    id: '36',
    title: 'BTCUSDT Chart',
    url: 'https://www.tradingview.com/chart/7S3hVp5C/',
    category: 'Trading',
    description: 'Bitcoin / TetherUS price chart.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'bitcoin chart',
  },
  {
    id: '37',
    title: 'Simply Wall St',
    url: 'https://simplywall.st/?view',
    category: 'Trading',
    description: 'Understand the stock market and make better investing decisions.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'investment analysis',
  },
  {
    id: '38',
    title: 'UFTFAST',
    url: 'https://oms.uftcl.com/login',
    category: 'Trading',
    description: 'Login page for UFTFAST.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'trading platform',
  },
  {
    id: '39',
    title: 'NetPlus New',
    url: 'https://cityinfinity.citybrokerageltd.com/',
    category: 'Trading',
    description: 'Trading platform by City Brokerage Ltd.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'brokerage terminal',
  },
  {
    id: '40',
    title: 'Amarstock',
    url: 'https://www.amarstock.com/',
    category: 'Trading',
    description: 'Share Market Tools For Dhaka Stock Exchange (DSE) Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'dse building',
  },
  {
    id: '41',
    title: 'Investing.com Bangladesh',
    url: 'https://www.investing.com/equities/bangladesh',
    category: 'Trading',
    description: 'Bangladesh Stock Market quotes, stock exchange news and analysis.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'bangladesh stocks',
  },
  {
    id: '42',
    title: 'Investing.com Technical Summary',
    url: 'https://www.investing.com/technical/personalized-quotes-technical-summary',
    category: 'Trading',
    description: 'Customizable technical analysis summary.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'technical chart',
  },
  {
    id: '43',
    title: 'Binance Spot Trading BTC/USDT',
    url: 'https://www.binance.com/en/trade/BTC_USDT?type=spot',
    category: 'Trading',
    description: 'Spot trading for Bitcoin against TetherUS on Binance.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'crypto exchange',
  },
  {
    id: '44',
    title: 'Moneycontrol',
    url: 'https://www.moneycontrol.com/',
    category: 'Trading',
    description: 'Business News Today: Stock and Share Market News, Economy and Finance News.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'financial news',
  },
  {
    id: '45',
    title: 'Gmail - aaz.bitu@gmail.com',
    url: 'https://mail.google.com/mail/u/6/#inbox',
    category: 'Email',
    description: 'Inbox for aaz.bitu@gmail.com.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'email client',
  },
  {
    id: '46',
    title: 'Gmail - ur.daudibrahim@gmail.com',
    url: 'https://mail.google.com/mail/u/1/#inbox',
    category: 'Email',
    description: 'Inbox for ur.daudibrahim@gmail.com.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'email interface',
  },
  {
    id: '47',
    title: 'Outlook Mail',
    url: 'https://outlook.office.com/mail/',
    category: 'Email',
    description: 'Outlook Mail for MD.DAUD IBRAHIM.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'outlook logo',
  },
  {
    id: '48',
    title: 'Messages for web',
    url: 'https://messages.google.com/web/conversations/CgjcFxeIxrOKahIEMTAyMw',
    category: 'Social',
    description: 'Use Messages for web to send SMS, MMS and RCS messages from your computer.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'texting messages',
  },
  {
    id: '49',
    title: 'Log In to Cisco',
    url: 'https://id.cisco.com/',
    category: 'Not use',
    description: 'Cisco login page.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'network hardware',
  },
  {
    id: '50',
    title: 'Networking Academy',
    url: 'https://www.netacad.com/portal/learning',
    category: 'Education',
    description: 'I\'m Learning | Networking Academy.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cisco networking',
  },
  {
    id: '51',
    title: 'Student Login - Udvash Unmesh',
    url: 'https://online.udvash-unmesh.com/Account/Login',
    category: 'Education',
    description: 'Student login portal for Udvash Unmesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'education login',
  },
  {
    id: '52',
    title: 'GIMSC | Student Interface',
    url: 'https://www.gimclive.edu-smart.info/student_interface.php',
    category: 'Education',
    description: 'Student interface for GIMSC.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'student portal',
  },
  {
    id: '53',
    title: 'Google Classroom',
    url: 'https://classroom.google.com/u/2/c/NTQ5Mjg2Nzk3NTY5',
    category: 'Education',
    description: 'EngReading Monday B26 8AM class.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online classroom',
  },
  {
    id: '54',
    title: 'My Account :: Freelancer Nasim',
    url: 'https://club.fnsoftwares.com/index.php',
    category: 'Work',
    description: 'Account page for Freelancer Nasim.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'freelancer profile',
  },
  {
    id: '55',
    title: 'Sark Computer',
    url: 'https://sarkcomputerbd.com/',
    category: 'Shopping',
    description: 'Computer hardware store.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'computer parts',
  },
  {
    id: '56',
    title: 'Chrome Music Lab',
    url: 'https://musiclab.chromeexperiments.com/',
    category: 'Entertainment',
    description: 'A website that makes learning music more accessible through fun, hands-on experiments.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'music creation',
  },
  {
    id: '57',
    title: 'NAVIFORCE NF1001 Luxury Mechanical Watch',
    url: 'https://www.naviforcewatchesbd.com/product/naviforce-nf1001-luxury-mechanical-watch/',
    category: 'Shopping',
    description: 'Product page for a Naviforce mechanical watch.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'luxury watch',
  },
  {
    id: '58',
    title: 'Ravens Giftshop BD',
    url: 'https://ravensgiftshopbd.com/',
    category: 'Shopping',
    description: 'Let Your Collections Be Ravens.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'gift shop',
  },
  {
    id: '59',
    title: 'Mathway | Algebra Problem Solver',
    url: 'https://www.mathway.com/Algebra',
    category: 'Education',
    description: 'Free math problem solver answers your algebra homework questions with step-by-step explanations.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'math problems',
  },
  {
    id: '60',
    title: 'ResearchGate',
    url: 'https://www.researchgate.net/',
    category: 'Education',
    description: 'The professional network for scientists and researchers.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'scientific research',
  },
  {
    id: '61',
    title: 'Daraz.com.bd',
    url: 'https://www.daraz.com.bd/#?',
    category: 'Shopping',
    description: 'Online shopping in Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online shopping',
  },
  {
    id: '62',
    title: 'y2mate',
    url: 'https://www.y2mate.com/en63',
    category: 'Utilities',
    description: 'Download video and audio from YouTube.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'video download',
  },
  {
    id: '63',
    title: 'grow.google',
    url: 'https://learndigital.withgoogle.com/digitalunlocked/course/digital-marketing/lesson/25',
    category: 'Education',
    description: 'Grow with Google offers free training and tools to help you grow your skills, career, or business.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online learning',
  },
  {
    id: '64',
    title: 'payoneer',
    url: 'https://myaccount.payoneer.com/ma/',
    category: 'Finance',
    description: 'A global payment platform.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online payments',
  },
  {
    id: '65',
    title: 'y2mate',
    url: 'https://y2meta.app/en33',
    category: 'Utilities',
    description: 'Download video and audio from YouTube.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'youtube downloader',
  },
  {
    id: '66',
    title: 'coinbase',
    url: 'https://www.coinbase.com/dashboard',
    category: 'Finance',
    description: 'A secure platform to buy, sell, and store cryptocurrency like Bitcoin, Ethereum, and more.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'crypto wallet',
  },
  {
    id: '67',
    title: 'TL-WR840N',
    url: 'http://192.168.0.2/',
    category: 'Utilities',
    description: 'Router admin page.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'router settings',
  },
  {
    id: '68',
    title: 'Photo in Information copy - Google Photos',
    url: 'https://photos.google.com/album/AF1QipPbtHsw6Y2bf4ttLOxhcn3O4NnmFASGMpDpjIUx/photo/AF1QipPiElPXF6mnujgX5-a9fn9yWOllqcL9riI0zWmn',
    category: 'Not use',
    description: 'A specific photo from a Google Photos album.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'photo album',
  },
  {
    id: '69',
    title: 'Home | Daudibrahim',
    url: 'https://xdaudibrahim.wixsite.com/daudibrahim',
    category: 'Portfolio',
    description: 'Personal portfolio website on Wix.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'personal website',
  },
  {
    id: '70',
    title: 'Microsoft Math Solver',
    url: 'https://math.microsoft.com/en',
    category: 'Education',
    description: 'Math Problem Solver & Calculator.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'mathematics formulas',
  },
  {
    id: '71',
    title: 'Google Scholar',
    url: 'https://scholar.google.com/schhp?hl=en&as_sdt=0,5',
    category: 'Education',
    description: 'A freely accessible web search engine that indexes the full text or metadata of scholarly literature.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'academic papers',
  },
  {
    id: '72',
    title: 'ToffeeShare',
    url: 'https://toffeeshare.com/',
    category: 'Utilities',
    description: 'Share files privately, fast and without size limit.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'file transfer',
  },
  {
    id: '73',
    title: 'toppr.com',
    url: 'https://www.toppr.com/ask/en-bh/',
    category: 'Education',
    description: 'An online learning platform.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online education',
  },
  {
    id: '74',
    title: 'Chat Blackbox: AI Code Generation',
    url: 'https://www.blackbox.ai/',
    category: 'AI',
    description: 'AI Code Generation, Code Chat, Code Search.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai coding',
  },
  {
    id: '75',
    title: 'Convert JPG to PNG Online',
    url: 'https://www.adobe.com/express/feature/image/convert/jpg-to-png',
    category: 'Utilities',
    description: 'Free image converter from Adobe Express.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'image format',
  },
  {
    id: '76',
    title: 'Google Search Console',
    url: 'https://search.google.com/u/1/search-console?resource_id=sc-domain%3Adaudibrahim.com',
    category: 'Utilities',
    description: 'Tools and reports to help you measure your site\'s Search traffic and performance.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'seo analytics',
  },
  {
    id: '77',
    title: 'Google Career Certificates',
    url: 'https://grow.google/certificates/',
    category: 'Education',
    description: 'Online Courses with Certificates from Google.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online certificate',
  },
  {
    id: '78',
    title: '3D Print Dining Table cover',
    url: 'https://www.daraz.com.bd/products/6-3-i373843046.html',
    category: 'Shopping',
    description: 'Product page for a 3D printed dining table cover.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'dining table',
  },
  {
    id: '79',
    title: 'Thangs: Trending 3D models',
    url: 'https://thangs.com/?sort=trending',
    category: 'Design',
    description: 'Free 3D models to download.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': '3d models',
  },
  {
    id: '80',
    title: 'LinkedIn Jobs',
    url: 'https://www.linkedin.com/jobs/search/?alertAction=viewjobs',
    category: 'Work',
    description: 'Job search on LinkedIn.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'job search',
  },
  {
    id: '81',
    title: 'What you imagine is what Vidu',
    url: 'https://www.vidu.studio/',
    category: 'AI',
    description: 'AI video generation studio.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai video',
  },
  {
    id: '82',
    title: 'The IEOM Society',
    url: 'https://www.xcdsystem.com/IEOM/member/member_home.cfm',
    category: 'Education',
    description: 'Member home for The IEOM Society.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'professional society',
  },
  {
    id: '83',
    title: 'A Good Movie To Watch',
    url: 'https://agoodmovietowatch.com/',
    category: 'Entertainment',
    description: 'Highly-rated, little-known movies and shows you can watch on your streaming services.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie recommendations',
  },
  {
    id: '84',
    title: 'Gofile - Cloud Storage',
    url: 'https://gofile.io/home',
    category: 'Utilities',
    description: 'A free file sharing and storage platform.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cloud storage',
  },
  {
    id: '85',
    title: 'Responses - Google Sheets',
    url: 'https://docs.google.com/spreadsheets/d/1q6LNYc1dSbEC8OVB4HpFI_sKRmKVKV4CdHVWQo29Sb0/edit?gid=1309563034#gid=1309563034',
    category: 'Work',
    description: 'Google Sheets for responses.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'spreadsheet data',
  },
  {
    id: '86',
    title: 'Google Cybersecurity Professional Certificate',
    url: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    category: 'Education',
    description: 'A professional certificate from Google on Coursera.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cybersecurity course',
  },
  {
    id: '87',
    title: 'Noodle Magazine',
    url: 'https://noodlemagazine.com/watch/-191660232_456247370',
    category: 'Entertainment',
    description: 'Online video content.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'entertainment news',
  },
  {
    id: '88',
    title: 'AVJOY',
    url: 'https://en.avjoy.me/video/47425/start-046-self-requirement-the-newlywed-wife-who-moved-to-a-higher-level-apartment-being-a-hunter-to-a-rich-man-drug',
    category: 'Entertainment',
    description: 'Video streaming site.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'video play',
  },
  {
    id: '89',
    title: 'Kimi.ai',
    url: 'https://kimi.ai/',
    category: 'AI',
    description: 'An AI assistant that can reason, analyze, and think deeply.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai technology',
  },
  {
    id: '90',
    title: 'AlternativeTo',
    url: 'https://alternativeto.net/',
    category: 'Utilities',
    description: 'Crowdsourced software recommendations.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'software icons',
  },
  {
    id: '91',
    title: 'Easy Load',
    url: 'https://easyload.robi.com.bd/pretups/dynamicReports/generate',
    category: 'Finance',
    description: 'Robi Easy Load service.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'mobile recharge',
  },
  {
    id: '92',
    title: 'Firsttrip',
    url: 'https://firsttrip.com/flight',
    category: 'Travel',
    description: 'Air Ticket Booking Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'airplane flight',
  },
  {
    id: '93',
    title: 'Anime-Planet',
    url: 'https://www.anime-planet.com/anime/watch-online/?page=3',
    category: 'Anime',
    description: 'Watch anime online. Large database of anime and manga.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime characters',
  },
  {
    id: '94',
    title: 'Aria the Natural - Google Search',
    url: 'https://www.google.com/search?q=Aria+the+Natural',
    category: 'Anime',
    description: 'Google search results for Aria the Natural.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime scenery',
  },
  {
    id: '95',
    title: 'blades of the guardians - Google Search',
    url: 'https://www.google.com/search?q=blades+of+the+guardians',
    category: 'Anime',
    description: 'Google search results for Blades of the Guardians.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'fantasy swords',
  },
  {
    id: '96',
    title: 'even given the worthless appraiser class - Google Search',
    url: 'https://www.google.com/search?q=even+given+the+worthless+appraiser+class',
    category: 'Anime',
    description: 'Google search results for a specific anime/manga title.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime fight',
  },
  {
    id: '97',
    title: 'Helck - Google Search',
    url: 'https://www.google.com/search?q=Helck',
    category: 'Anime',
    description: 'Google search results for Helck.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime adventure',
  },
  {
    id: '98',
    title: 'gamers anime - Google Search',
    url: 'https://www.google.com/search?q=gamers+anime',
    category: 'Anime',
    description: 'Google search results for Gamers! anime.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime gamers',
  },
  {
    id: '99',
    title: 'durara - Google Search',
    url: 'https://www.google.com/search?q=durara',
    category: 'Anime',
    description: 'Google search results for Durarara!!.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'city night',
  },
  {
    id: '100',
    title: 'MyAnimeList.net',
    url: 'https://myanimelist.net/',
    category: 'Anime',
    description: 'Anime and manga database and community.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime collection',
  },
  {
    id: '101',
    title: 'HiAnime.to',
    url: 'https://hianime.to/',
    category: 'Anime',
    description: 'Watch Anime Online, Free Anime Streaming.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime streaming',
  },
  {
    id: '102',
    title: '9anime.to',
    url: 'https://9anime.to/?13',
    category: 'Anime',
    description: 'Watch Anime Online, Watch English Anime Online Subbed, Dubbed.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime library',
  },
  {
    id: '103',
    title: 'Zoro.to',
    url: 'https://zoro.to/',
    category: 'Anime',
    description: 'Watch Anime Online, Free Anime Streaming Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime hero',
  },
  {
    id: '104',
    title: 'Anix.to',
    url: 'https://anix.to/home',
    category: 'Anime',
    description: 'Watch Anime Online, Free Anime Streaming.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime action',
  },
  {
    id: '105',
    title: 'AnimeDao',
    url: 'https://animedao.to/',
    category: 'Anime',
    description: 'Watch your favorite anime online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime series',
  },
  {
    id: '106',
    title: 'Gogoanime',
    url: 'https://gogoanime.hu/',
    category: 'Anime',
    description: 'Watch anime online, English anime online HD.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime style',
  },
  {
    id: '107',
    title: 'KissAnime',
    url: 'https://kissanime.com.ru/kissanime-home.html',
    category: 'Anime',
    description: 'Watch anime online free on KissAnime.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime romance',
  },
  {
    id: '108',
    title: 'AnimeSuge',
    url: 'https://animesuge.to/home',
    category: 'Anime',
    description: 'Watch HD Anime Free with English Subbed, Dubbed.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'fantasy anime',
  },
  {
    id: '109',
    title: 'Masterani.me',
    url: 'https://masteranime.tv/masterani.me',
    category: 'Anime',
    description: 'Watch. Anime. Online. Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'master anime',
  },
  {
    id: '110',
    title: 'AnimeHeaven',
    url: 'https://animeheaven.ru/animeheaven.eu',
    category: 'Anime',
    description: 'Watch Anime Online Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'heavenly anime',
  },
  {
    id: '111',
    title: 'Tubi',
    url: 'https://tubitv.com/home',
    category: 'Entertainment',
    description: 'Watch Free Movies and TV Shows Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'tv shows',
  },
  {
    id: '112',
    title: 'Chia-Anime',
    url: 'https://chia-anime.su/info.html',
    category: 'Anime',
    description: 'Watch anime free online in high quality.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cute anime',
  },
  {
    id: '113',
    title: 'CONtv',
    url: 'https://www.contv.com/browse-movie/',
    category: 'Entertainment',
    description: 'Watch Free Movies, TV shows and Comic Con Panels Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'comic con',
  },
  {
    id: '114',
    title: 'Anime-Planet',
    url: 'https://www.anime-planet.com/',
    category: 'Anime',
    description: 'Anime and manga database and community.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime world',
  },
  {
    id: '115',
    title: 'DubbedAnime.biz',
    url: 'https://dubbedanime.biz/',
    category: 'Anime',
    description: 'Watch Anime Online English Dubbed & Anime Subbed.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'dubbed anime',
  },
  {
    id: '116',
    title: 'Nanowerk Anime Streaming',
    url: 'https://www.nanowerk.com/25-Best-Free-Anime-Streaming-Sites-to-Watch-Anime-Online.php',
    category: 'Anime',
    description: 'List of best free anime streaming sites.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime list',
  },
  {
    id: '117',
    title: 'Aniplus-Asia',
    url: 'https://www.aniplus-asia.com/',
    category: 'Anime',
    description: 'The Ultimate Platform for All Things Anime.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'asian anime',
  },
  {
    id: '118',
    title: 'Manganato',
    url: 'https://manganato.com/index.php',
    category: 'Manga',
    description: 'Read Manga Online Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'manga panels',
  },
  {
    id: '119',
    title: 'Simkl',
    url: 'https://simkl.com/anime/',
    category: 'Anime',
    description: 'Watch and Track Movies, Anime, TV Shows.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'tracking list',
  },
  {
    id: '120',
    title: 'AnimeLand',
    url: 'https://animeland.fr/',
    category: 'Anime',
    description: 'French anime news and community site.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime magazine',
  },
  {
    id: '121',
    title: 'Chia-Anime',
    url: 'https://chia-anime.cc/',
    category: 'Anime',
    description: 'Watch Anime Online in High Quality.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'hd anime',
  },
  {
    id: '122',
    title: 'AnimeKisa.tv',
    url: 'https://animekisa.tv/',
    category: 'Anime',
    description: 'Find & Watch Anime, Subbed & Dubbed.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime database',
  },
  {
    id: '123',
    title: 'Animetake',
    url: 'https://animetake.tv/',
    category: 'Anime',
    description: 'Watch anime in high quality.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime watching',
  },
  {
    id: '124',
    title: 'animepahe',
    url: 'https://animepahe.com/',
    category: 'Anime',
    description: 'Okay-ish anime website.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime website',
  },
  {
    id: '125',
    title: 'YugenAnime',
    url: 'https://yugenanime.tv/',
    category: 'Anime',
    description: 'Watch HD Anime for Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'free anime',
  },
  {
    id: '126',
    title: 'WCOstream',
    url: 'https://www.wcostream.com/',
    category: 'Entertainment',
    description: 'Watch cartoons online, Watch anime online, English dub anime.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cartoon characters',
  },
  {
    id: '127',
    title: '9animeTV',
    url: 'https://9animetv.to/home#',
    category: 'Anime',
    description: 'Best free anime to watch in HD quality.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'hd quality',
  },
  {
    id: '128',
    title: 'MangaFire',
    url: 'https://mangafire.to/home',
    category: 'Manga',
    description: 'Read Manga Online Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'manga art',
  },
  {
    id: '129',
    title: 'HiAnime Top Airing',
    url: 'https://hianime.to/top-airing',
    category: 'Anime',
    description: 'Watch Top Airing Anime SUBBED/DUBBED Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'top anime',
  },
  {
    id: '130',
    title: 'MasterAnime.vip',
    url: 'https://masteranime.vip/masterani.me',
    category: 'Anime',
    description: 'Watch anime online for free on MasterAni.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime portal',
  },
  {
    id: '131',
    title: 'MAL exporter',
    url: 'https://malscraper.azurewebsites.net/',
    category: 'Utilities',
    description: 'MyAnimeList data exporter.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'data export',
  },
  {
    id: '132',
    title: 'band of brothers - Google Search',
    url: 'https://www.google.com/search?q=band+of+brothers',
    category: 'Entertainment',
    description: 'Google search for the series Band of Brothers.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'war movie',
  },
  {
    id: '133',
    title: 'GitHub',
    url: 'https://github.com/',
    category: 'Coding',
    description: 'A provider of Internet hosting for software development and version control using Git.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'code repository',
  },
  {
    id: '134',
    title: 'GitHub: MdDaudIbrahim',
    url: 'https://github.com/MdDaudIbrahim',
    category: 'Portfolio',
    description: 'Personal GitHub profile.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'developer profile',
  },
  {
    id: '135',
    title: 'Portfolio - Md.Daud Ibrahim',
    url: 'https://mddaudibrahim.github.io/Portfolio/',
    category: 'Portfolio',
    description: 'Personal portfolio website.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'web design',
  },
  {
    id: '136',
    title: 'AIUB CGPA Calculator',
    url: 'https://mddaudibrahim.github.io/Aiub-Cgpa-Calculator/',
    category: 'Utilities',
    description: 'A tool to calculate CGPA for AIUB students.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'calculator app',
  },
  {
    id: '137',
    title: 'Dada Trading House',
    url: 'https://mddaudibrahim.github.io/Dada-Trading-House/',
    category: 'Work',
    description: 'Website for Dada Trading House.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'trading company',
  },
  {
    id: '138',
    title: 'Course Solution',
    url: 'https://course-solution.netlify.app/',
    category: 'Education',
    description: 'An educational resource website.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online courses',
  },
  {
    id: '139',
    title: 'Movie & Anime Picker',
    url: 'https://mddaudibrahim.github.io/Movie-Anime-Picker/',
    category: 'Entertainment',
    description: 'A tool to help you pick a movie or anime to watch.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie picker',
  },
  {
    id: '140',
    title: 'AIUB Course Info',
    url: 'https://aiub.brainbird.org/',
    category: 'Education',
    description: 'Information about courses at AIUB.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'course catalog',
  },
  {
    id: '141',
    title: 'Netlify',
    url: 'https://www.netlify.com/',
    category: 'Coding',
    description: 'A platform for automating web projects.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'web hosting',
  },
  {
    id: '142',
    title: 'Supabase',
    url: 'https://supabase.com/dashboard/organizations',
    category: 'Coding',
    description: 'The open source Firebase alternative.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'database platform',
  },
  {
    id: '143',
    title: 'J.A.R.V.I.S Personal Assistant',
    url: 'https://github.com/GauravSingh9356/J.A.R.V.I.S',
    category: 'AI',
    description: 'Personal Assistant built using python libraries.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai assistant',
  },
  {
    id: '144',
    title: 'Jarvis-AI-System',
    url: 'https://github.com/dsaakash/Jarvis-AI-System/',
    category: 'AI',
    description: 'Jarvis is an AI chatbot developed to respond to user queries via text and voice.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'voice interface',
  },
  {
    id: '145',
    title: 'J.A.R.V.I.S voice assistant',
    url: 'https://github.com/BolisettySujith/J.A.R.V.I.S',
    category: 'AI',
    description: 'A voice assistant which can be used to interact with your computer.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'sound waves',
  },
  {
    id: '146',
    title: 'JARVIS-AGI',
    url: 'https://github.com/SreejanPersonal/JARVIS-AGI',
    category: 'AI',
    description: 'AI Powered Voice Assistant with Real Human Capabilities.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'artificial intelligence',
  },
  {
    id: '147',
    title: 'jarvis.py',
    url: 'https://github.com/HemantKArya/JARVIS_Project1/blob/master/jarvis.py',
    category: 'Coding',
    description: 'Python script for a Jarvis-like assistant.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'python code',
  },
  {
    id: '148',
    title: 'GitHub Profile Readme Generator',
    url: 'https://rahuldkjain.github.io/gh-profile-readme-generator/',
    category: 'Utilities',
    description: 'A tool to generate beautiful GitHub profile READMEs.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'github profile',
  },
  {
    id: '149',
    title: 'Build Your Own X',
    url: 'https://github.com/codecrafters-io/build-your-own-x',
    category: 'Coding',
    description: 'Master programming by recreating your favorite technologies from scratch.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'coding projects',
  },
  {
    id: '150',
    title: 'Coolify',
    url: 'https://coolify.io/',
    category: 'Coding',
    description: 'An open-source and self-hostable Heroku / Netlify alternative.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'server hosting',
  },
  {
    id: '151',
    title: 'AIUB Routine Generate',
    url: 'https://rra.onukrom.xyz/',
    category: 'Utilities',
    description: 'A tool to generate class routines for AIUB.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'class schedule',
  },
  {
    id: '152',
    title: 'Free Business Website Templates',
    url: 'https://www.free-css.com/template-categories/business?start=24',
    category: 'Design',
    description: 'A collection of free business website templates.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'website templates',
  },
  {
    id: '153',
    title: 'DadaTradingHouse-DTH',
    url: 'https://mddaudibrahim.github.io/DadaTradingHouse-DTH/',
    category: 'Work',
    description: 'Website for Dada Trading House.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'business website',
  },
  {
    id: '154',
    title: 'GitLab',
    url: 'https://about.gitlab.com/',
    category: 'Coding',
    description: 'The most-comprehensive AI-powered DevSecOps platform.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'devops platform',
  },
  {
    id: '155',
    title: 'SourceForge',
    url: 'https://sourceforge.net/',
    category: 'Coding',
    description: 'Compare, Download & Develop Open Source & Business Software.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'open source',
  },
  {
    id: '156',
    title: 'Bitbucket',
    url: 'https://bitbucket.org/product/',
    category: 'Coding',
    description: 'Git solution for teams using Jira.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'git repository',
  },
  {
    id: '157',
    title: 'Vercel Projects',
    url: 'https://vercel.com/ursavagex-gmailcoms-projects',
    category: 'Coding',
    description: 'Dashboard for Vercel projects.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'web deployment',
  },
  {
    id: '158',
    title: 'Course Solution',
    url: 'https://aiub-course-solution.netlify.app/',
    category: 'Education',
    description: 'Your Academic Success Partner.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'academic success',
  },
  {
    id: '159',
    title: 'The Impact of Online and Offline Large Language Models',
    url: 'https://index.ieomsociety.org/index.cfm/article/view/ID/28377',
    category: 'AI',
    description: 'Research article on the impact of LLMs.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'research paper',
  },
  {
    id: '160',
    title: 'virattt/ai-hedge-fund',
    url: 'https://github.com/virattt/ai-hedge-fund',
    category: 'AI',
    description: 'An AI Hedge Fund Team project on GitHub.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'hedge fund',
  },
  {
    id: '161',
    title: 'emmabostian/developer-portfolios',
    url: 'https://github.com/emmabostian/developer-portfolios',
    category: 'Portfolio',
    description: 'A list of developer portfolios for your inspiration.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'developer community',
  },
  {
    id: '162',
    title: 'GitHub Student Developer Pack',
    url: 'https://education.github.com/pack',
    category: 'Education',
    description: 'The best developer tools, free for students.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'student pack',
  },
  {
    id: '163',
    title: 'mannaandpoem/OpenManus',
    url: 'https://github.com/mannaandpoem/OpenManus',
    category: 'AI',
    description: 'OpenManus is Coming.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'open source ai',
  },
  {
    id: '164',
    title: 'System Prompts and Models of AI Tools',
    url: 'https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools',
    category: 'AI',
    description: 'A repository of system prompts for various AI tools.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai prompts',
  },
  {
    id: '165',
    title: 'kortix-ai/suna',
    url: 'https://github.com/kortix-ai/suna',
    category: 'AI',
    description: 'Suna - Open Source Generalist AI Agent.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai agent',
  },
  {
    id: '166',
    title: 'Daud Ibrahim - Portfolio',
    url: 'https://daudibrahim.netlify.app/',
    category: 'Portfolio',
    description: 'Personal portfolio deployed on Netlify.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'portfolio page',
  },
  {
    id: '167',
    title: 'GitHub Education',
    url: 'https://education.github.com/campus_experts',
    category: 'Education',
    description: 'GitHub Campus Experts program.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'education program',
  },
  {
    id: '168',
    title: 'DEV Community - Campus Experts Applications',
    url: 'https://dev.to/gh-campus-experts/campus-experts-applications-august-2024-46pl',
    category: 'Education',
    description: 'Information about applying to be a GitHub Campus Expert.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'developer community',
  },
  {
    id: '169',
    title: 'GitHub Campus Experts',
    url: 'https://github.com/campus-experts',
    category: 'Education',
    description: 'Official GitHub organization for Campus Experts.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'student community',
  },
  {
    id: '170',
    title: 'GitHub Education for Students',
    url: 'https://github.com/education/students',
    category: 'Education',
    description: 'Resources for students from GitHub Education.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'student developers',
  },
  {
    id: '171',
    title: 'GitHub Certifications',
    url: 'https://resources.github.com/learn/certifications/',
    category: 'Education',
    description: 'Highlight your expertise with GitHub Certifications.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'tech certification',
  },
  {
    id: '172',
    title: 'Awesome n8n Templates',
    url: 'https://github.com/enescingoz/awesome-n8n-templates',
    category: 'Coding',
    description: 'A curated collection of n8n templates.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'automation templates',
  },
  {
    id: '173',
    title: '2025 AI College Jobs',
    url: 'https://github.com/speedyapply/2025-AI-College-Jobs',
    category: 'Work',
    description: '2025 AI/ML internship & new graduate job list updated daily.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'job list',
  },
  {
    id: '174',
    title: 'Name.com: Free Domain for Students',
    url: 'https://www.name.com/github-students',
    category: 'Utilities',
    description: 'Free domain offer for students.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'domain name',
  },
  {
    id: '175',
    title: 'BrowserStack',
    url: 'https://www.browserstack.com/',
    category: 'Coding',
    description: 'Most Reliable App & Cross Browser Testing Platform.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'browser testing',
  },
  {
    id: '176',
    title: 'The High Society Chapter 15',
    url: 'https://hentai20.io/the-high-society-chapter-15/',
    category: 'Entertainment',
    description: 'Read Webtoon 18+.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'webtoon comic',
  },
  {
    id: '177',
    title: 'The High Society Chapter 18',
    url: 'https://hentai20.io/the-high-society-chapter-18/',
    category: 'Entertainment',
    description: 'Read Webtoon 18+.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'comic panel',
  },
  {
    id: '178',
    title: 'SONE-574 [English Subtitle]',
    url: 'https://www4.javhdporn.net/v13/video/sone-574/',
    category: 'Entertainment',
    description: 'JAV HD Porn video.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'actress model',
  },
  {
    id: '179',
    title: 'OFJE-558 Unparalleled Divine Breast Beauty',
    url: 'https://www4.javhdporn.net/v12/video/ofje-558/',
    category: 'Entertainment',
    description: 'JAV HD Porn video.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'beautiful woman',
  },
  {
    id: '180',
    title: 'Excel Data Filter & Report Tool',
    url: 'https://excle-data-management.netlify.app/',
    category: 'Utilities',
    description: 'A tool for filtering and reporting on Excel data.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'data management',
  },
  {
    id: '181',
    title: 'Best FTP Server BD List',
    url: 'https://www.pcbuilderbd.com/networking/best-bdix-ftp-server-bd-list/',
    category: 'Utilities',
    description: 'List of best BDIX FTP servers in Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'server room',
  },
  {
    id: '182',
    title: 'All FTP Servers In Bangladesh (BDIX)',
    url: 'https://banglazoom.com/ftp-servers-bangladesh/',
    category: 'Utilities',
    description: 'List of all FTP servers in Bangladesh (BDIX).',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'data center',
  },
  {
    id: '183',
    title: 'HD Anime Wallpaper',
    url: 'https://www.wallpaperflare.com/anime-dual-monitor-multi-screen-widescreen-wallpaper-pxobq',
    category: 'Design',
    description: 'Dual monitor anime wallpaper.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'anime wallpaper',
  },
  {
    id: '184',
    title: 'Professional CV Writing',
    url: 'https://ghoorilearning.com/courses/professional-cv-writing',
    category: 'Education',
    description: 'Course on professional CV writing.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'resume writing',
  },
  {
    id: '185',
    title: 'Bangladesh NID Application System',
    url: 'https://services.nidw.gov.bd/nid-pub/',
    category: 'Utilities',
    description: 'Official NID application system for Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'government portal',
  },
  {
    id: '186',
    title: 'Surokkha',
    url: 'https://surokkha.gov.bd/',
    category: 'Utilities',
    description: 'COVID-19 vaccine registration for Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'vaccine registration',
  },
  {
    id: '187',
    title: 'Link3 Selfcare',
    url: 'https://selfcare.link3.net/home/tickets',
    category: 'Utilities',
    description: 'Selfcare portal for Link3 customers.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'customer portal',
  },
  {
    id: '188',
    title: 'India, East India Company Coin',
    url: 'https://www.galata.co.uk/copy-of---india-east-india-company-bengal-presidency-silver-quarter-rupee-1831-35-calcutta-mint-mintmark-crescent',
    category: 'Hobbies',
    description: 'Bengal Presidency silver quarter rupee from 1831-35.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'old coin',
  },
  {
    id: '189',
    title: 'Biddr - Coin Auction',
    url: 'https://www.biddr.com/auctions/lcg/browse?a=141&l=126154',
    category: 'Hobbies',
    description: 'London Coin Galleries auction on Biddr.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'coin auction',
  },
  {
    id: '190',
    title: '1889 HALF RUPEE QUEEN VICTORIA',
    url: 'https://www.ebay.ca/itm/386103481851',
    category: 'Hobbies',
    description: 'Rare silver coin of British India Empire on eBay.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'queen victoria',
  },
  {
    id: '191',
    title: 'BRITISH INDIA 1862 VICTORIA QUEEN ONE RUPEE',
    url: 'https://www.ebay.com/itm/365101362694',
    category: 'Hobbies',
    description: 'Rare silver coin on eBay.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'old money',
  },
  {
    id: '192',
    title: '1889 $1 MS | Coin Explorer | NGC',
    url: 'https://www.ngccoin.com/coin-explorer/united-states/dollars/morgan-dollars-1878-1921/17188/1889-1-ms/',
    category: 'Hobbies',
    description: 'Information about an 1889 Morgan Dollar.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'morgan dollar',
  },
  {
    id: '193',
    title: '1/4 Rupee 1918 Silver Coin King George V',
    url: 'https://collectionyatra.com/product/1-4-rupee-1918-silver-coin-of-king-george-v-british-india-collectible-coins/',
    category: 'Hobbies',
    description: 'Collectible British India coin.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'king george',
  },
  {
    id: '194',
    title: 'British India 1940 George vi King Emperor 1/4 Rupee',
    url: 'https://indiancoinshub.com/product/british-india-1940-george-vi-king-emperor-1-4-rupee-fa7189/',
    category: 'Hobbies',
    description: '1/4 Rupee coin from 1940.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'emperor coin',
  },
  {
    id: '195',
    title: '1 rupee 1911, India - British',
    url: 'https://en.ucoin.net/coin/british_india-1-rupee-1911/?tid=52550',
    category: 'Hobbies',
    description: 'Coin value information on uCoin.net.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'one rupee',
  },
  {
    id: '196',
    title: '1889 HALF RUPEE QUEEN VICTORIA RARE SILVER COIN',
    url: 'https://www.ebay.com/itm/144877475770',
    category: 'Hobbies',
    description: 'Rare silver coin of British India Empire on eBay.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'silver coin',
  },
  {
    id: '197',
    title: 'Polymarket',
    url: 'https://polymarket.com/',
    category: 'Finance',
    description: 'The World\'s Largest Prediction Market.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'prediction market',
  },
  {
    id: '198',
    title: 'Digital Bangladesh Quiz Rules',
    url: 'https://quiz.digitalbangladesh.gov.bd/rules',
    category: 'Education',
    description: 'Rules for the Digital Bangladesh Quiz.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'quiz competition',
  },
  {
    id: '199',
    title: 'Digital Bangladesh Quiz Home',
    url: 'https://quiz.digitalbangladesh.gov.bd/home',
    category: 'Education',
    description: 'Homepage for the Digital Bangladesh Quiz.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'bangladesh flag',
  },
  {
    id: '200',
    title: 'Tinkercad - Learning the Moves',
    url: 'https://www.tinkercad.com/things/120lCXbbw14-learning-the-moves/edit?lessonid=EABLWFTIQ2KHDSZ&projectid=O2C1PXBIQ2KHCOD&collectionid=O2C1PXBIQ2KHCOD#/lesson-viewer',
    category: 'Design',
    description: 'A 3D design lesson on Tinkercad.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': '3d design',
  },
  {
    id: '201',
    title: 'Imgur: Upload',
    url: 'https://imgur.com/upload',
    category: 'Utilities',
    description: 'The magic of the Internet. Imgur is an online image sharing community and image host.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'image upload',
  },
  {
    id: '202',
    title: 'Router Admin',
    url: 'http://192.168.0.1/YGDPPCTBEAXFQSHB/userRpm/Index.htm',
    category: 'Utilities',
    description: 'Admin page for a TL-WR940N router.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'network configuration',
  },
  {
    id: '203',
    title: 'Wix.com Dashboard',
    url: 'https://www.wix.com/dashboard/91e9e299-f794-45d5-9173-f4561348401b/home?referralInfo=my-sites',
    category: 'Design',
    description: 'Your Wix website dashboard.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'website builder',
  },
  {
    id: '204',
    title: 'Epic Games Store',
    url: 'https://www.epicgames.com/store/en-US/',
    category: 'Gaming',
    description: 'A digital PC game storefront for Windows and macOS, operated by Epic Games.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'video games',
  },
  {
    id: '205',
    title: 'Google Workspace Marketplace',
    url: 'https://gsuite.google.com/marketplace',
    category: 'Utilities',
    description: 'Find third-party apps that integrate with Google Workspace.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'app marketplace',
  },
  {
    id: '206',
    title: 'Cinehub24',
    url: 'http://www.cinehub24.com/',
    category: 'Entertainment',
    description: 'Watch live online free HD Movies and Tv series.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie streaming',
  },
  {
    id: '207',
    title: 'FTPBD',
    url: 'http://ftpbd.net/',
    category: 'FTP',
    description: 'FTP server for various content.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'file server',
  },
  {
    id: '208',
    title: 'Samonline FTP',
    url: 'http://172.16.50.4/',
    category: 'FTP',
    description: 'Samonline FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'local network',
  },
  {
    id: '209',
    title: '123MoviesFree',
    url: 'https://ww2.123moviesfree.net/',
    category: 'Entertainment',
    description: 'Watch HD Movies Online Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'free movies',
  },
  {
    id: '210',
    title: 'UpdateLand Free Movies',
    url: 'https://www.updateland.com/websites-watch-free-movies-online-without-downloading/#2_Vumoo',
    category: 'Entertainment',
    description: 'A list of sites to watch free movies online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie website',
  },
  {
    id: '211',
    title: 'Poki - Free Online Games',
    url: 'https://poki.com/',
    category: 'Gaming',
    description: 'The ultimate online playground. Free online games, no downloads required.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online games',
  },
  {
    id: '212',
    title: 'FlixHQ',
    url: 'https://flixhq.bz/home',
    category: 'Entertainment',
    description: 'Watch Series Online Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'tv series',
  },
  {
    id: '213',
    title: 'Microsoft Designer Image Creator',
    url: 'https://designer.microsoft.com/image-creator',
    category: 'AI',
    description: 'AI-powered image creator from Microsoft Designer.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai image',
  },
  {
    id: '214',
    title: 'FTPBD INDEX SERVER',
    url: 'http://server5.ftpbd.net/#blog',
    category: 'FTP',
    description: 'Index of an FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'server index',
  },
  {
    id: '215',
    title: 'Kissasian',
    url: 'https://kissasian.com.lv/',
    category: 'Entertainment',
    description: 'Watch Asian Drama and Shows Free in English Sub.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'asian drama',
  },
  {
    id: '216',
    title: 'server3.ftpbd.net',
    url: 'http://server3.ftpbd.net/',
    category: 'FTP',
    description: 'FTP server index.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'file directory',
  },
  {
    id: '217',
    title: 'Vegamovies',
    url: 'https://vegamovies.mu/',
    category: 'Entertainment',
    description: 'Download Bollywood And South Indian Hindi Dubbed Movies For Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'bollywood movies',
  },
  {
    id: '218',
    title: 'movieverse.one',
    url: 'https://movieverse.one/?s=Marco&e_search_props=b5314a1-317',
    category: 'Entertainment',
    description: 'Movie streaming website.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie posters',
  },
  {
    id: '219',
    title: 'HDTodayTV',
    url: 'https://www.hdtodaytv.tv/home',
    category: 'Entertainment',
    description: 'Free Movies and Free Series Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'streaming service',
  },
  {
    id: '220',
    title: 'FlixHQ',
    url: 'https://flixhq.to/home',
    category: 'Entertainment',
    description: 'Free Movies and Free Series.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie library',
  },
  {
    id: '221',
    title: 'Nkiri',
    url: 'https://nkiri.com/',
    category: 'Entertainment',
    description: 'Download free Hollywood Movies, Series and Dramas.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'hollywood movies',
  },
  {
    id: '222',
    title: 'Gooddrama',
    url: 'https://gooddrama.site/',
    category: 'Entertainment',
    description: 'Korean Series, Shows And Movies English Sub Online Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'korean drama',
  },
  {
    id: '223',
    title: 'Dramanice',
    url: 'https://ww3.dramanice.video/',
    category: 'Entertainment',
    description: 'Watch Korean Drama & Asian Shows Free English Subs.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'asian shows',
  },
  {
    id: '224',
    title: 'Dramacool',
    url: 'https://dramacool.com.tr/',
    category: 'Entertainment',
    description: 'Asian Drama, Movies and Shows English Sub.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'drama cool',
  },
  {
    id: '225',
    title: 'ViewAsian',
    url: 'https://viewasian.lol/',
    category: 'Entertainment',
    description: 'The Best Platform for Asian Drama Lovers.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'asian actress',
  },
  {
    id: '226',
    title: 'Watcho',
    url: 'https://www.watcho.com/',
    category: 'Entertainment',
    description: 'Watch Indian Web Series, TV Shows, Movies & Live Sports Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'indian series',
  },
  {
    id: '227',
    title: 'Playflix',
    url: 'https://www.playflix.app/',
    category: 'Entertainment',
    description: 'One Stop Entertainment App.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'entertainment app',
  },
  {
    id: '228',
    title: 'STARFILX',
    url: 'https://www.starfilx.in/',
    category: 'Entertainment',
    description: 'Kdrama streaming site.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'kdrama scene',
  },
  {
    id: '229',
    title: 'MoviesMod',
    url: 'https://moviesmod.surf/',
    category: 'Entertainment',
    description: 'Download movies from various sources.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie download',
  },
  {
    id: '230',
    title: 'crazyctg.com',
    url: 'https://crazyctg.com/',
    category: 'FTP',
    description: 'FTP server for content.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'file transfer',
  },
  {
    id: '231',
    title: 'deranged movie - Google Search',
    url: 'https://www.google.com/search?q=deranged+movie',
    category: 'Entertainment',
    description: 'Search results for the movie Deranged.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'horror movie',
  },
  {
    id: '232',
    title: 'henna ie - Google Search',
    url: 'https://www.google.com/search?q=henna+ie',
    category: 'Entertainment',
    description: 'Search results for Henna ie.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie still',
  },
  {
    id: '233',
    title: 'warau matryoshka - Google Search',
    url: 'https://www.google.com/search?q=warau+matryoshka',
    category: 'Entertainment',
    description: 'Search results for Warau Matryoshka.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'japanese drama',
  },
  {
    id: '234',
    title: 'better call saul - Google Search',
    url: 'https://www.google.com/search?q=better+call+saul',
    category: 'Entertainment',
    description: 'Search results for Better Call Saul.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'lawyer show',
  },
  {
    id: '235',
    title: 'walking dead - Google Search',
    url: 'https://www.google.com/search?q=walking+dead',
    category: 'Entertainment',
    description: 'Search results for The Walking Dead.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'zombie apocalypse',
  },
  {
    id: '236',
    title: 'the mind hunter - Google Search',
    url: 'https://www.google.com/search?q=the+mind+hunter',
    category: 'Entertainment',
    description: 'Search results for Mindhunter.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'crime thriller',
  },
  {
    id: '237',
    title: 'black mirror - Google Search',
    url: 'https://www.google.com/search?q=black+mirror',
    category: 'Entertainment',
    description: 'Search results for Black Mirror.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'dystopian future',
  },
  {
    id: '238',
    title: 'ozark - Google Search',
    url: 'https://www.google.com/search?q=ozark',
    category: 'Entertainment',
    description: 'Search results for Ozark.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'crime drama',
  },
  {
    id: '239',
    title: 'prison break - Google Search',
    url: 'https://www.google.com/search?q=prison+break',
    category: 'Entertainment',
    description: 'Search results for Prison Break.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'prison escape',
  },
  {
    id: '240',
    title: 'from - Google Search',
    url: 'https://www.google.com/search?q=from',
    category: 'Entertainment',
    description: 'Search results for the TV series "From".',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'horror series',
  },
  {
    id: '241',
    title: 'the boys - Google Search',
    url: 'https://www.google.com/search?q=the+boys',
    category: 'Entertainment',
    description: 'Search results for the TV series "The Boys".',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'superhero show',
  },
  {
    id: '242',
    title: 'blade runner - Google Search',
    url: 'https://www.google.com/search?q=blade+runner',
    category: 'Entertainment',
    description: 'Search results for Blade Runner.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'sci-fi movie',
  },
  {
    id: '243',
    title: 'stripchatgirls',
    url: 'https://stripchatgirls.com/Georgina_21',
    category: 'Entertainment',
    description: 'Webcam show.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'webcam model',
  },
  {
    id: '244',
    title: 'FlixHQ Alternative',
    url: 'https://videoconverter.wondershare.com/movie-subtitling/flixhq-alternative.html',
    category: 'Entertainment',
    description: 'Article about alternatives to FlixHQ.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'streaming sites',
  },
  {
    id: '245',
    title: 'Fmovies',
    url: 'https://ww4.fmovies.co/24/',
    category: 'Entertainment',
    description: 'Watch Free Movies Online.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'free movie',
  },
  {
    id: '246',
    title: 'SolarMovies',
    url: 'https://solarmovie2.com/home.html',
    category: 'Entertainment',
    description: 'Watch FREE Movies Online & TV shows.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'solar movie',
  },
  {
    id: '247',
    title: 'nevertheless - Google Search',
    url: 'https://www.google.com/search?q=nevertheless',
    category: 'Entertainment',
    description: 'Search results for the K-drama "Nevertheless".',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'romance drama',
  },
  {
    id: '248',
    title: 'vikram movie - Google Search',
    url: 'https://www.google.com/search?q=vikram+movie',
    category: 'Entertainment',
    description: 'Search results for the movie "Vikram".',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'action movie',
  },
  {
    id: '249',
    title: 'Cinehub24 Live TV',
    url: 'http://livetv.cinehub24.com/',
    category: 'Entertainment',
    description: 'Dhaka Flix!! Live TV streaming.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'live tv',
  },
  {
    id: '250',
    title: 'CrazyCTG',
    url: 'http://crazyctg.com/',
    category: 'FTP',
    description: 'FTP Server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ftp site',
  },
  {
    id: '251',
    title: 'ShowTimeBD',
    url: 'http://www.showtimebd.com/',
    category: 'FTP',
    description: 'FTP Server for entertainment.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'showtime logo',
  },
  {
    id: '252',
    title: 'Timenai.com',
    url: 'http://timenai.com/',
    category: 'FTP',
    description: 'Watch live online free 10000+ HD Movies and Tv series.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online entertainment',
  },
  {
    id: '253',
    title: 'Ocean of Games',
    url: 'https://oceanofgames.com/',
    category: 'Gaming',
    description: 'Download games for free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'game download',
  },
  {
    id: '254',
    title: 'YTS.monster',
    url: 'https://yts.monster/',
    category: 'Entertainment',
    description: 'The Official Home of YIFY Movies Torrent Download.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie torrent',
  },
  {
    id: '255',
    title: '1337x',
    url: 'https://1337x.to/home/',
    category: 'Entertainment',
    description: 'Download verified torrents: movies, music, games, software.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'torrent site',
  },
  {
    id: '256',
    title: 'Torrent Downloads',
    url: 'https://torrentdownloads.mrunblock.icu/',
    category: 'Entertainment',
    description: 'Download free torrents!',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'torrent download',
  },
  {
    id: '257',
    title: 'MLWBD.life',
    url: 'https://mlwbd.life/',
    category: 'Entertainment',
    description: 'Download HEVC movies.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie lovers',
  },
  {
    id: '258',
    title: 'Skidrow & Reloaded Games',
    url: 'https://www.skidrowreloaded.com/',
    category: 'Gaming',
    description: 'Download PC games.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'pc games',
  },
  {
    id: '259',
    title: 'Crohasit',
    url: 'https://crohasit.net/',
    category: 'Gaming',
    description: 'Download PC Games For Free.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cracked games',
  },
  {
    id: '260',
    title: 'The Pirate Bay',
    url: 'https://thepiratebay10.org/search/adobe%20photoshop%20/1/99/0',
    category: 'Entertainment',
    description: 'The galaxy\'s most resilient bittorrent site.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'pirate ship',
  },
  {
    id: '261',
    title: 'MLWBD.beauty',
    url: 'https://mlwbd.beauty/',
    category: 'Entertainment',
    description: 'Download HEVC movies.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie posters',
  },
  {
    id: '262',
    title: 'MODYOLO',
    url: 'https://modyolo.com/',
    category: 'Gaming',
    description: 'Free MOD APK Game & Premium APP for Android.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'android apps',
  },
  {
    id: '263',
    title: 'FileHippo.com',
    url: 'https://filehippo.com/',
    category: 'Utilities',
    description: 'Download free software for Windows.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'software download',
  },
  {
    id: '264',
    title: 'Samonline',
    url: 'http://172.16.50.5/',
    category: 'FTP',
    description: 'Samonline FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'local server',
  },
  {
    id: '265',
    title: 'Showtime BD',
    url: 'http://www.showtimebd.com/',
    category: 'FTP',
    description: 'Showtime BD FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie server',
  },
  {
    id: '266',
    title: 'Naturalbd',
    url: 'http://naturalbd.com/',
    category: 'FTP',
    description: 'Biggest Online Movie Server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'natural bd',
  },
  {
    id: '267',
    title: 'Ebox Live',
    url: 'http://fs.ebox.live/',
    category: 'FTP',
    description: 'Ebox Live FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ebox server',
  },
  {
    id: '268',
    title: 'FTP BD Server 2',
    url: 'http://server2.ftpbd.net/',
    category: 'FTP',
    description: 'B.net Index Server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'server rack',
  },
  {
    id: '269',
    title: 'Sam Online',
    url: 'https://samftp.com/',
    category: 'FTP',
    description: 'Sam Online FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'online server',
  },
  {
    id: '270',
    title: 'Funtime BD',
    url: 'http://funtimebd.com/',
    category: 'FTP',
    description: 'Fun Time Bangladesh.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'fun time',
  },
  {
    id: '271',
    title: 'Timepass BD',
    url: 'http://ftp.timepassbd.live/',
    category: 'FTP',
    description: 'Timepass BD FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'time pass',
  },
  {
    id: '272',
    title: 'Anime & Cartoon TV Series FTP',
    url: 'http://server5.ftpbd.net/FTP-5/Anime%20%26%20Cartoon%20TV%20Series/',
    category: 'FTP',
    description: 'FTP for Anime & Cartoons.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'cartoon folder',
  },
  {
    id: '273',
    title: 'CSBD Game Server',
    url: 'http://games.cybersolutionsbd.com/',
    category: 'Gaming',
    description: 'Game Server by Cyber Solutions BD.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'game server',
  },
  {
    id: '274',
    title: 'English Movies 2022 FTP',
    url: 'http://server2.ftpbd.net/FTP-2/English%20Movies/2022/',
    category: 'FTP',
    description: 'FTP folder for English movies from 2022.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'movie folder',
  },
  {
    id: '275',
    title: 'CTGHall',
    url: 'http://www.ctghall.com/',
    category: 'FTP',
    description: 'FTP server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ctg hall',
  },
  {
    id: '276',
    title: 'SKYVIEW ONLINE',
    url: 'http://timepassbd.live/',
    category: 'FTP',
    description: 'Biggest Online Movie Server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'sky view',
  },
  {
    id: '277',
    title: 'Old FTP BD',
    url: 'https://old.ftpbd.net/',
    category: 'FTP',
    description: 'Old FTP BD server.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'old server',
  },
  {
    id: '278',
    title: 'Download file | iLovePDF',
    url: 'https://www.ilovepdf.com/download/6shrk83Adkvxn511nxxc7r12z60s3zzp2mh8cl23vvrtzw8j56px03f6zdqp6llnb9n60809dAbxr8v3rj97fg3n4zldc38387gwnfpfldbk8vr9r190ybs882p0Axvgsh15jc91dmdc5sjAdbm6364tc1jyfd6mh0xxstndA9n9jgzjfryq/32',
    category: 'Utilities',
    description: 'File download from iLovePDF.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'pdf download',
  },
  {
    id: '279',
    title: 'bitten tech - Google Drive',
    url: 'https://drive.google.com/drive/folders/1D75pAX0Gfpt4v7m1XkURMPY_BRTgOAsw',
    category: 'Utilities',
    description: 'Google Drive folder for bitten tech.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'file folder',
  },
  {
    id: '280',
    title: 'Turnitin',
    url: 'https://www.turnitin.com/',
    category: 'Education',
    description: 'Technology solutions for the global education community.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'plagiarism checker',
  },
  {
    id: '281',
    title: 'Course Hero',
    url: 'https://www.coursehero.com/',
    category: 'Education',
    description: 'Online learning platform with course-specific study resources.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'study resources',
  },
  {
    id: '282',
    title: 'Perplexity AI',
    url: 'https://www.perplexity.ai/',
    category: 'AI',
    description: 'An AI-powered conversational search engine.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai search',
  },
  {
    id: '283',
    title: 'LMArena',
    url: 'https://lmarena.ai/',
    category: 'AI',
    description: 'Arena for Large Language Models.',
    image: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'ai battle',
  }
];

export const categories = Array.from(new Set(bookmarks.map(b => b.category))).sort();
