[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Next.js handles routing, so we don't need custom redirects
# The @netlify/plugin-nextjs handles this automatically
